#!/bin/sh
### BEGIN INIT INFO
# Provides:          auto_shutdown
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Auto shutdown
# Description:       Automatically poweroff VM after certain period of idle
### END INIT INFO

case "$1" in
start)
    setsid /bin/auto_shutdown.sh >/dev/null 2>&1 < /dev/null &
    ;;
*)
    ;;
esac
